### ISSUE TITLE
gulp.dest() wrong path if foldername contains "*"

### ISSUE THREAD

**Issue by happen-studio** [gulpjs/gulp#2750]
If the name of the folder contains the character "*", then gulp.dest() does not work properly. 
In my example, gulp saves the css file in:

*workspaces / project01 / css / *workspaces / project01 / css / 

my folder structure: 
```
+ *workspaces
           + project01 (gulp folder)
                 + _build
                 + css 
```

my code: 
```
…
function styles(done) {
    gulp.src('_build/css/*.css')
			         .pipe(plumber())
			         .pipe(gcmq())
			         .pipe(csso())
			         .pipe(plumber())
			         .pipe(gulp.dest('css/'))
.pipe(browserSync.stream({match: '**/*.css'}));
done();
}
…
```

* OSX version 13.2.1
* node version 19.3.0
* npm version 9.8.1
* gulp version (CLI 2.3.0, local 4.0.2)

**Comment by peteichuk** [comment]
I have this problem too. I did not change versions in package.json, but some updates in gulp destroyed my project.

**Comment by yocontra** [comment]
This should be fixed in gulp 5

**Comment by peteichuk** [comment]
> This should be fixed in gulp 5

Hello, it is not a good idea to make some updates in the current version without updating the minor version, etc. just need to roll back any changes to the normal state to the end of the 2023 year. Now we have problems with `**/*` with error messages "Error: ENOENT: no such file or directory".

**Comment by peteichuk** [comment]
> This should be fixed in gulp 5
Hello, I migrated my project to Gulp 5 today, but the problem is still for me.

**Comment by yocontra** [comment]
@peteichuk Can you post some code that demonstrates your issue?

**Comment by peteichuk** [comment]
> @peteichuk Can you post some code that demonstrates your issue?

Hello, sure. This is a simple code, but the project is very large and uses multiple configurations in a foreach loop, pushing other tasks. However, there's an issue with excluding "dest" files, which results in having bad images (this images not opening) at their original size and some problematic JS files. I don't understand where the problem lies—whether it's with the mapping in the template string src ('apps/_shared/libs/*') or memory for Node.js. But ever since I started creating new builds after 2023, I've been experiencing this issue, even though I haven't made any updates to the config or the project.

Code:

```
const gulp = require('gulp'),
    minify = require('gulp-minify'),
    sass = require('gulp-sass'),
    cssmin = require('gulp-cssnano'),
    prefix = require('gulp-autoprefixer'),
    buble = require('gulp-buble');

const tasks = [];

function addToTaskSharedDir() {
    let task = 'copyLibs-shared';
    tasks.push(task);

    gulp.task(task, function () {
        return gulp.src('apps/_shared/libs/*')
          .pipe(gulp.dest('public/shared/libs'));
    });

    task = 'copyImages-shared';
    tasks.push(task);

    gulp.task(task, function () {
        return gulp.src('apps/_shared/images/**/*')
          .pipe(gulp.dest('public/shared/images'));
    });

    task = 'buildJS-shared';
    tasks.push(task);

    gulp.task(task, function () {
        return gulp.src(['apps/_shared/javascripts/*.js'])
          .pipe(buble())
          .pipe(minify())
          .pipe(gulp.dest('public/shared/js'))
    });

    task = 'buildCSS-shared';
    tasks.push(task);

    gulp.task(task, function () {
        return gulp.src(['apps/_shared/scss/*.scss'])
          .pipe(sass())
          .pipe(prefix({
              overrideBrowserslist: ['last 2 versions'],
              cascade: false
          }))
          .pipe(cssmin())
          .pipe(gulp.dest('public/shared/css'));
    });
}

addToTaskSharedDir();

gulp.task('build', gulp.series(tasks));
```

Thanks!
