### ISSUE TITLE
gulp.watch: running the same tasks over each other

### ISSUE THREAD

**Issue by avp** [gulpjs/gulp#557]
I'm having some issues with time-consuming tasks that are watched by gulp.

Suppose task B depends on task A (i.e. task A must run before task B). I watch some files, and I run task B when the files change. then, after task A completes and task B is running, I save the files again - this results in task A starting up again, before task B finishes. Then task B never gets rerun with the second save and I have to go back and resave, and wait for gulp to finish running both task A and B again when it would not have been necessary.

Is there a way for gulp to recognize this overlap in dependencies and either ensure that task B *always* runs after task A or simply restart both tasks on file change?

**Comment by himynameisdave** [comment]
Article about task-dependency in Gulp:
[woot woot task dependencies](https://medium.com/@dave_lunny/task-dependencies-in-gulp-b885c1ab48f0)

**Comment by contra** [comment]
Cool - I'll close this since it has been fixed in gulp 4. You can use the gulp4 branch from github for now until we publish

**Comment by adambuczynski** [comment]
This is still an issue for me with gulp 4.0. After doing a find & replace in Atom I get the following:

![ss](https://www.dropbox.com/s/yn11tj6jbuzfro5/Screenshot%202015-07-23%2012.18.27.png?dl=1)

The task:

```javascript
/**
 * Watch client side code
 */
function watchClientCode() {
  gulp.watch([
    config.assets.client.js.app,
    config.assets.client.html
  ], gulp.series(lintCode, testClientCode, buildAppJs, buildIndex));
}
```
